version: '3'

tasks:
  cleanup:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go mod tidy
      - rm -f test_coverage.out

  test:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go test -v ./...

  test:coverage:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go test -v -cover -coverprofile=test_coverage.out
      - go tool cover -html=test_coverage.out

  vet:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go vet ./...

  # see `golangci-lint help linters` to see all linters
  # Pass -E/--enable to enable linter and -D/--disable to disable:
  # `golangci-lint run --disable-all -E errcheck`
  # using all checks and verbose output: $ golangci-lint run ./... --enable-all
  lint:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - golangci-lint run ./...
    
  # installing development & ci dependencies
  install:deps:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.6